#!/bin/bash

#Info about my computer science students from students database
echo -e "\n~~ My Computer Science Students ~~\n"
PSQL="psql -X --username=freecodecamp --dbname=students --no-align --tuples-only -c"
echo -e "\nFirst name, last name, and GPA of students with a 4.0 GPA:"
echo "$($PSQL "Select first_name,last_name,gpa from students Where gpa=4.0")"
echo -e "\nAll course names whose first letter is before 'D' in the alphabet:"
echo "$($PSQL "Select course from courses where course < 'D';")"
echo -e "\nFirst name, last name, and GPA of students whose last name begins with an 'R' or after and have a GPA greater than 3.8 or less than 2.0:"
echo "$($PSQL "Select first_name,last_name,gpa from students where last_name >= 'R' and (gpa > 3.8 or gpa < 2.0);")"
echo -e "\nLast name of students whose last name contains a case insensitive 'sa' or have an 'r' as the second to last letter:"
echo "$($PSQL "Select last_name from students where (last_name ilike '%sa%' or last_name like '%r_');")"
echo -e "\nFirst name, last name, and GPA of students who have not selected a major and either their first name begins with 'D' or they have a GPA greater than 3.0:"
echo "$($PSQL "Select first_name,last_name,gpa from students Where major_id is null and (first_name like 'D%' or gpa > 3.0);")"
echo -e "\nCourse name of the first five courses, in reverse alphabetical order, that have an 'e' as the second letter or end with an 's':"
echo "$($PSQL "Select course from courses where course like '_e%' or course like '%s' Order By course DESC Limit 5;")"
echo -e "\nAverage GPA of all students rounded to two decimal places:"
echo "$($PSQL "Select round(avg(gpa),2) from students;")"
echo -e "\nMajor ID, total number of students in a column named 'number_of_students', and average GPA rounded to two decimal places in a column name 'average_gpa', for each major ID in the students table having a student count greater than 1:"
echo "$($PSQL "Select major_id,Count(*) as number_of_students,round(avg(gpa),2) as average_gpa from students GROUP BY major_id Having Count(*) > 1;")"
echo -e "\nList of majors, in alphabetical order, that either no student is taking or has a student whose first name contains a case insensitive 'ma':"
echo "$($PSQL "Select major from majors left join students on majors.major_id=students.major_id WHERE student_id is null or first_name ilike '%ma%' ORDER BY major;")"
echo -e "\nList of unique courses, in reverse alphabetical order, that no student or 'Obie Hilpert' is taking:"
echo "$($PSQL "Select DISTINCT(course) from students FULL JOIN majors USING(major_id) FULL JOIN majors_courses USING(major_id) RIGHT JOIN courses USING(course_id) where student_id is null or first_name='Obie' ORDER BY course DESC;")"
echo -e "\nList of courses, in alphabetical order, with only one student enrolled:"
echo "$($PSQL "Select course from students INNER JOIN majors USING(major_id) INNER JOIN majors_courses USING(major_id) INNER JOIN courses USING(course_id) GROUP BY course Having COUNT(course)=1 ORDER BY course;")"

#! Otra prueba

PSQL="psql --username=freecodecamp --dbname=worldcup --no-align --tuples-only -c"

# Do not change code above this line. Use the PSQL variable above to query your database.

echo -e "\nTotal number of goals in all games from winning teams:"
echo "$($PSQL "SELECT SUM(winner_goals) FROM games")"

echo -e "\nTotal number of goals in all games from both teams combined:"
echo $(($($PSQL "SELECT SUM(winner_goals + opponent_goals) FROM games") ))

echo -e "\nAverage number of goals in all games from the winning teams:"
echo "$($PSQL "SELECT AVG(winner_goals) FROM games")"

echo -e "\nAverage number of goals in all games from the winning teams rounded to two decimal places:"
echo "$($PSQL "SELECT ROUND(AVG(winner_goals),2) FROM games")"

echo -e "\nAverage number of goals in all games from both teams:"
echo  $($PSQL "SELECT AVG(winner_goals+opponent_goals) FROM games")

echo -e "\nMost goals scored in a single game by one team:"
echo  $($PSQL "SELECT MAX(winner_goals) FROM games")

echo -e "\nNumber of games where the winning team scored more than two goals:"
echo  $($PSQL "SELECT Count(*) FROM games WHERE winner_goals > 2")

echo -e "\nWinner of the 2018 tournament team name:"
echo  $($PSQL "SELECT name FROM teams FULL JOIN games ON teams.team_id=games.winner_id WHERE round like 'Final' and year=2018 ")

echo -e "\nList of teams who played in the 2014 'Eighth-Final' round:"
echo  $($PSQL "SELECT name FROM teams FULL JOIN games ON teams.team_id=games.winner_id or teams.team_id=games.opponent_id where year=2014 and round like 'Eighth-Final' ORDER BY name;")

echo -e "\nList of unique winning team names in the whole data set:"
echo  $($PSQL "SELECT DISTINCT(name) FROM teams FULL JOIN games ON teams.team_id=games.winner_id where game_id is not null GROUP BY name HAVING COUNT(*)>=1 ORDER BY name;")

echo -e "\nYear and team name of all the champions:"
echo  $($PSQL "SELECT year,name FROM teams FULL JOIN games ON teams.team_id=games.winner_id where round like 'Final' ORDER BY year;")

echo -e "\nList of teams that start with 'Co':"
echo  $($PSQL "SELECT name FROM teams WHERE name like 'Co%'")
